# Generated by Django 4.2.17 on 2024-12-12 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('reviewed', '已审核'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL, verbose_name='标注者')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='file_management.document', verbose_name='文档')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_annotations', to=settings.AUTH_USER_MODEL, verbose_name='审核者')),
            ],
            options={
                'verbose_name': '标注',
                'verbose_name_plural': '标注',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset', models.IntegerField(verbose_name='开始位置')),
                ('end_offset', models.IntegerField(verbose_name='结束位置')),
                ('text', models.CharField(max_length=500, verbose_name='事件文本')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='annotation.annotation', verbose_name='标注')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.eventtype', verbose_name='事件类型')),
            ],
            options={
                'verbose_name': '事件标注',
                'verbose_name_plural': '事件标注',
            },
        ),
        migrations.CreateModel(
            name='ArgumentAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset', models.IntegerField(verbose_name='开始位置')),
                ('end_offset', models.IntegerField(verbose_name='结束位置')),
                ('text', models.CharField(max_length=500, verbose_name='论元文本')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='annotation.eventannotation', verbose_name='事件')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_management.argumentrole', verbose_name='论元角色')),
            ],
            options={
                'verbose_name': '论元标注',
                'verbose_name_plural': '论元标注',
            },
        ),
    ]
