# Generated by Django 4.2.17 on 2024-12-12 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='事件类型名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='project_management.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '事件类型',
                'verbose_name_plural': '事件类型',
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ArgumentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='论元角色名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必需')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argument_roles', to='event_management.eventtype', verbose_name='事件类型')),
            ],
            options={
                'verbose_name': '论元角色',
                'verbose_name_plural': '论元角色',
                'unique_together': {('name', 'event_type')},
            },
        ),
    ]
